/*import 'package:equatable/equatable.dart';

class MenuItem extends Equatable{
  final int id;
  final int restaurantId;
  final String name;
  final String category;
  final String description;
  final double price;

  MenuItem({
    required this.id,
    required this.restaurantId,
    required this.name,
    required this.category,
    required this.description,
    required this.price
    });
    
      @override
      // TODO: implement props
      List<Object?> get props => [
          id,
          restaurantId,
          name,
          category,
          description,
          price,
        ];

    static List<MenuItem> menuItems = [
      MenuItem(
        id: 1,
        restaurantId: 1,
        name: 'Margherita',
        category: 'Pizza',
        description: 'Tomato, mozzarella, basil',
        price: 9.99,
      ),
      MenuItem(
        id: 2,
        restaurantId: 1,
        name: 'Pepperoni',
        category: 'Pizza',
        description: 'Tomato, mozzarella, pepperoni',
        price: 10.99,
      ),
      MenuItem(
        id: 3,
        restaurantId: 1,
        name: 'Garlic Bread',
        category: 'Sides',
        description: 'Garlic butter, parsley',
        price: 4.99,
      ),
      MenuItem(
        id: 4,
        restaurantId: 1,
        name: 'Chicken Wings',
        category: 'Sides',
        description: 'BBQ, buffalo, or sweet chili',
        price: 6.99,
      ),
      MenuItem(
        id: 5,
        restaurantId: 1,
        name: 'Mighty Meaty',
        category: 'Pizza',
        description: 'Pepperoni, sausage, ham, bacon, ground beef',
        price: 11.99,
      ),
      MenuItem(
        id: 6,
        restaurantId: 1,
        name: 'Veggie',
        category: 'Pizza',
        description: 'Tomato, mozzarella, mushrooms, peppers, olives',
        price: 10.99,
      ),
      MenuItem(
        id: 7,
        restaurantId: 1,
        name: 'Cheeseburger Pizza',
        category: 'Pizza',
        description: 'Beef, cheddar, tomato, onion, pickles',
        price: 12.99,
      ),
      MenuItem(
        id: 8,
        restaurantId: 1,
        name: 'Chicken Dippers',
        category: 'Sides',
        description: 'Chicken, garlic',
        price: 6.99,
      ),
      MenuItem(
        id: 9,
        restaurantId: 1,
        name: 'Garlic Bread with Cheese',
        category: 'Sides',
        description: 'Garlic butter, parsley, mozzarella',
        price: 5.99,
      ),
      MenuItem(
        id: 10,
        restaurantId: 2,
        name: 'BBQ Chicken',
        category: 'Pizza',
        description: 'BBQ sauce, chicken, bacon, onion',
        price: 11.99,
      ),
      MenuItem(
        id: 11,
        restaurantId: 1,
        name: 'Hawaiian',
        category: 'Pizza',
        description: 'Tomato, mozzarella, ham, pineapple',
        price: 10.99,
      ),
      MenuItem(
        id: 11,
        restaurantId: 2,
        name: 'Cheese Burger',
        category: 'Burger',
        description: 'Beef, cheddar, tomato, onion, pickles',
        price: 10.99,
      ),
      MenuItem(
        id: 12,
        restaurantId: 2,
        name: 'Chicken Burger',
        category: 'Burger',
        description: 'Chicken, lettuce, tomato, mayo',
        price: 10.99,
      ),
      MenuItem(
        id: 13,
        restaurantId: 2,
        name: 'Veggie Burger',
        category: 'Burger',
        description: 'Veggie patty, lettuce, tomato, mayo',
        price: 10.99,
      ),
      MenuItem(
        id: 14,
        restaurantId: 2,
        name: 'Fries',
        category: 'Sides',
        description: 'Potato, salt',
        price: 3.99,
      ),
      MenuItem(
        id: 15,
        restaurantId: 2,
        name: 'Onion Rings',
        category: 'Sides',
        description: 'Onion, batter',
        price: 4.99,
      ),
      MenuItem(
        id: 16,
        restaurantId: 2,
        name: 'Milkshake',
        category: 'Drinks',
        description: 'Milk, ice cream, flavor',
        price: 5.99,
      ),
      MenuItem(
        id: 17,
        restaurantId: 2,
        name: 'Coke',
        category: 'Drinks',
        description: 'Coca cola',
        price: 2.99,
      ),
      MenuItem(
        id: 18,
        restaurantId: 2,
        name: 'Diet Coke',
        category: 'Drinks',
        description: 'Diet coca cola',
        price: 2.99,
      ),
      MenuItem(
        id: 19,
        restaurantId: 3,
        name: 'Chocolate Cake',
        category: 'Dessert',
        description: 'Chocolate, sponge',
        price: 4.99,
      ),
      MenuItem(
        id: 20,
        restaurantId: 3,
        name: 'Cheesecake',
        category: 'Dessert',
        description: 'Cheese, biscuit',
        price: 4.99,
      ),
      MenuItem(
        id: 21,
        restaurantId: 3,
        name: 'Carrot Cake',
        category: 'Dessert',
        description: 'Carrot, sponge',
        price: 4.99,
      ),
      MenuItem(
        id: 22,
        restaurantId: 3,
        name: 'Red Velvet Cake',
        category: 'Dessert',
        description: 'Red velvet, sponge',
        price: 4.99,
      ),
      MenuItem(
        id: 23,
        restaurantId: 4,
        name: 'Coffee',
        category: 'Drinks',
        description: 'Coffee, milk',
        price: 2.99,
      ),
      MenuItem(
        id: 24,
        restaurantId: 4,
        name: 'Tea',
        category: 'Drinks',
        description: 'Tea, milk',
        price: 2.99,
      ),
      MenuItem(
        id: 25,
        restaurantId: 4,
        name: 'Orange Juice',
        category: 'Drinks',
        description: 'Orange juice',
        price: 2.99,
      ),
      MenuItem(
        id: 26,
        restaurantId: 4,
        name: 'Apple Juice',
        category: 'Drinks',
        description: 'Apple juice',
        price: 2.99,
      ),
      MenuItem(
        id: 27,
        restaurantId: 4,
        name: 'Water',
        category: 'Drinks',
        description: 'Water',
        price: 1.99,
      ),
      MenuItem(
        id: 28,
        restaurantId: 5,
        name: 'Chicken Caesar',
        category: 'Salad',
        description: 'Chicken breast, romaine, parmesan, croutons',
        price: 1.99,
      ),
      MenuItem(
        id: 29,
        restaurantId: 5,
        name: 'Greek Salad',
        category: 'Salad',
        description: 'Lettuce, tomato, cucumber, olives, feta',
        price: 1.99,
      ),
      MenuItem(
        id: 30,
        restaurantId: 5,
        name: 'Cobb Salad',
        category: 'Salad',
        description: 'Chicken, bacon, avocado, egg, tomato',
        price: 1.99,
      ),
      MenuItem(
        id: 31,
        restaurantId: 5,
        name: 'Caesar Salad',
        category: 'Salad',
        description: 'Romaine, parmesan, croutons',
        price: 1.99,
      ),
      MenuItem(
        id: 32,
        restaurantId: 5,
        name: 'Tuna Salad',
        category: 'Salad',
        description: 'Tuna, lettuce, tomato, cucumber',
        price: 1.99,
      ),

  ];
  
}
*/