// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYUhGGUrGoZfVQGUu6Hz8fzinnF52-sMM',
    appId: '1:811246386671:web:f786c8bf033458561a8a1a',
    messagingSenderId: '811246386671',
    projectId: 'flutter-delivery-app-a5d3d',
    authDomain: 'flutter-delivery-app-a5d3d.firebaseapp.com',
    storageBucket: 'flutter-delivery-app-a5d3d.appspot.com',
    measurementId: 'G-XKDC3BMEPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbc3CzUL6u0p5n5sBvak71AmtxGrh23Q',
    appId: '1:811246386671:android:3199ff7a4cfe87bc1a8a1a',
    messagingSenderId: '811246386671',
    projectId: 'flutter-delivery-app-a5d3d',
    storageBucket: 'flutter-delivery-app-a5d3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdYrFRgRUoMjhLSUbQX3D_2WrGIpby35c',
    appId: '1:811246386671:ios:652756d81955b5541a8a1a',
    messagingSenderId: '811246386671',
    projectId: 'flutter-delivery-app-a5d3d',
    storageBucket: 'flutter-delivery-app-a5d3d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdYrFRgRUoMjhLSUbQX3D_2WrGIpby35c',
    appId: '1:811246386671:ios:51958208222ffc291a8a1a',
    messagingSenderId: '811246386671',
    projectId: 'flutter-delivery-app-a5d3d',
    storageBucket: 'flutter-delivery-app-a5d3d.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
